---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by opsoft.
--- DateTime: 2023/2/9 15:32
----- -- 锁的key
---- local key=KEYS[1]
---- -- 当前线程标识
---- local threadID=ARGV[1]
--
---- 获取锁中的线程标识
local id = redis.call('get',KEYS[1])
---- 比较线程id和锁中的线程标识
if(id==ARGV[1]) then
   return redis.call("del",KEYS[1])
end
return 0